version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
    - 27017:27017
    volumes:
      - "/Users/faisalaieissa/Desktop"
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
    - 8091:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
